### ISSUE TITLE
pycdio & libcdio issues

### ISSUE THREAD

**Issue by TJFOE** [whipper-team/whipper#238]
Hi,

I installed whipper by hand on Kubuntu 17.10 from git. After "whipper drive analyze"

I get:
File "/usr/local/lib/python2.7/dist-packages/whipper-0.6.0-py2.7.egg/whipper/command/cd.py", line 22, in <module>
    import cdio
ImportError: No module named cdio

Any idea, what I can do? Installed is:
libcdio-cdda1
libcdio-paranoia1
libcdio-utils
libcdio-dev
libcdio-cdda-dev
libcdio-paranoia-dev
libcdio13

Regards
Thomas

**Comment by a10footsquirrel** [comment]
Do you have [pycdio](https://pypi.python.org/pypi/pycdio/) installed?

**Comment by TJFOE** [comment]
I did this - like described on the website:

apt-get install python-dev
apt-get install libcdio-dev
apt-get install libiso9660-dev
apt-get install swig pkg-config

**Comment by a10footsquirrel** [comment]
That installs the dependencies of pycdio, I think. You need to install pycdio itself as well.

**Comment by a10footsquirrel** [comment]
I don't know what version of cdio is the default on ubuntu 17.10 but you need pycdio version 0.20 AFAIK. Try the tar you can find [here](https://pypi.python.org/pypi/pycdio/0.20).

**Comment by TJFOE** [comment]
Yes. That is what I did.

**Comment by a10footsquirrel** [comment]
The version is different from what I can tell. (2.0.0 and 0.20)

**Comment by TJFOE** [comment]
I downloaded this meanwhile and I am running in new errors:
http://git.savannah.gnu.org/cgit/libcdio.git

Error in makefile, line 427:
Makefile:427: die Regel für Ziel „libcdio.info“ scheiterte
make[2]: *** [libcdio.info] Fehler 127

line 427 means:
sharedstatedir = ${prefix}/com

whatever that means...

**Comment by TJFOE** [comment]
This solved the error:

sudo apt-get update
Install texinfo deb package:
sudo apt-get install texinfo

Now it seems good ... but a new error:
make[2]: *** Keine Regel vorhanden, um das Ziel „cd-drive.1“, 
  benötigt von „all-am“, zu erstellen.  Schluss.

**Comment by TJFOE** [comment]
No one an idea how to come out of this new error?

**Comment by TJFOE** [comment]
Kubuntu 17.10 has libcdio version 0.83 installed = max. version in sources

**Comment by TJFOE** [comment]
I have solved this problem for me this way: I downgraded to pycdio version 17 and using libcdio version 0.83 (I tried several other things which did not work):

sudo apt-get install python-pip
sudo apt-get install python-dev libcdio-dev libiso9660-dev swig pkg-config
sudo pip install pycdio==0.17

**Comment by TJFOE** [comment]
I reopen this issue. Because whipper starts but doesn't work correctly at all. I don't know, if it is a totally different problem. The problems:

- I have two devices and can only start with /dev/sr0 (what is the unused device). I cannot adress /dev/sr1

- If I use /dev/sr0 with "whipper offset find -o 6" (+6 is the correct offset for LG Electronics - BD-RE BH16NS40) and if I use any of the reference CDs, I get always:

Checking device /dev/sr0
Trying read offset 6 ...
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 121250348
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
WARNING: cannot rip with offset 6...    
No matching offset found.
Consider trying again with a different disc.

**Comment by GitHubGeek** [comment]
A related issue. `pycdio==0.17` doesn't work at all. Upgrade to `==0.20` would make the traceback go away:

```
$ whipper -h
Traceback (most recent call last):
  File "/home/ghg1988/.local/share/virtualenvs/pipenv-whipper-QlXKNnGk/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.6.0', 'console_scripts', 'whipper')()
  File "/home/ghg1988/.local/share/virtualenvs/pipenv-whipper-QlXKNnGk/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ghg1988/.local/share/virtualenvs/pipenv-whipper-QlXKNnGk/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2752, in load_entry_point
    return ep.load()
  File "/home/ghg1988/.local/share/virtualenvs/pipenv-whipper-QlXKNnGk/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/ghg1988/.local/share/virtualenvs/pipenv-whipper-QlXKNnGk/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ghg1988/.local/share/virtualenvs/pipenv-whipper-QlXKNnGk/local/lib/python2.7/site-packages/whipper-0.6.0-py2.7.egg/whipper/command/main.py", line 11, in <module>
    from whipper.command import cd, offset, drive, image, accurip, debug
  File "/home/ghg1988/.local/share/virtualenvs/pipenv-whipper-QlXKNnGk/local/lib/python2.7/site-packages/whipper-0.6.0-py2.7.egg/whipper/command/cd.py", line 22, in <module>
    import cdio
  File "/home/ghg1988/.local/share/virtualenvs/pipenv-whipper-QlXKNnGk/local/lib/python2.7/site-packages/cdio.py", line 20, in <module>
    import pycdio
  File "/home/ghg1988/.local/share/virtualenvs/pipenv-whipper-QlXKNnGk/local/lib/python2.7/site-packages/pycdio.py", line 76, in <module>
    CDIO_READ_MODE_AUDIO = _pycdio.CDIO_READ_MODE_AUDIO
AttributeError: 'module' object has no attribute 'CDIO_READ_MODE_AUDIO'
```

Running Ubuntu 16.04 LTS

```
$ dpkg -l | grep cdio
ii  libcdio-cdda-dev:amd64          0.83-4.2ubuntu1  amd64        library to read and control digital audio CDs (development files)
ii  libcdio-cdda1:amd64             0.83-4.2ubuntu1  amd64        library to read and control digital audio CDs
ii  libcdio-dev:amd64               0.83-4.2ubuntu1  amd64        library to read and control CD-ROM (development files)
ii  libcdio-paranoia1:amd64         0.83-4.2ubuntu1  amd64        library to read digital audio CDs with error correction
ii  libcdio-utils                   0.83-4.2ubuntu1  amd64        sample applications based on the CDIO libraries
ii  libcdio13:amd64                 0.83-4.2ubuntu1  amd64        library to read and control CD-ROM
```

**Comment by thomas-mc-work** [comment]
Yes, I have. Though on Debian 10 (buster).

**Comment by frankongithub18** [comment]
I found a solution for Ubuntu 18.04 to get Whipper running.

First at all install the missing cd-paranoia dependency, i follow the official instruction from launchpad here https://bugs.launchpad.net/ubuntu/+source/libcdio/+bug/1750264.

After this i checked all dependencies for pycdio to build, keep an eye on libiso9660-dev.
This library why ever was missing after upgrade from 16.04.
Then i manually build the sources from tar package and install it.

After this  everything works as with whipper version 0.5.1.
Have fun ;-)

**Comment by walterav1984** [comment]
@frankongithub18 
I can confirm that by installing the cd-paranoia&libcdio packages from deb-multimedia the latest whipper git pull is also working for me on Ubuntu 18.04 amd64.
