### ISSUE TITLE
"AttributeError: Program instance has no attribute '_presult'" when ripping

### ISSUE THREAD

**Issue by Freso** [whipper-team/whipper#369]
https://github.com/whipper-team/whipper/commit/16b0d8dc295d8576f863c39cffc9009d20a63937 introduced code calling `self._presult.persist()` but neither `_presult` nor `persist()` is defined anywhere in the code, causing ripping to fail:

```python-traceback
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
eject: Cd-rom-kommandoen luk skuffen mislykkedes: Inddata/uddata-fejl
Track 1 finished, found 11 Q sub-channels with CRC errors
Track 2 finished, found 9 Q sub-channels with CRC errors
Track 3 finished, found 9 Q sub-channels with CRC errors
Track 4 finished, found 13 Q sub-channels with CRC errors
Track 5 finished, found 10 Q sub-channels with CRC errors
Track 6 finished, found 13 Q sub-channels with CRC errors
Track 7 finished, found 24 Q sub-channels with CRC errors
Track 8 finished, found 17 Q sub-channels with CRC errors
Track 9 finished, found 18 Q sub-channels with CRC errors
Track 10 finished, found 17 Q sub-channels with CRC errors
Track 11 finished, found 23 Q sub-channels with CRC errors
Track 12 finished, found 47 Q sub-channels with CRC errors
CDDB disc id: a00c300c
MusicBrainz disc id hbJzXWQkBk3ZvIquY7axbmk4f.I-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+12+234197+150+19022+32740+57727+80737+98750+120870+139937+161450+179300+195412+214337&tracks=12&id=hbJzXWQkBk3ZvIquY7axbmk4f.I-
Disc duration: 00:52:00.626, 12 audio tracks

Matching releases:

Artist  : Viktoria Tolstoy
Title   : För älskad
Duration: 00:51:59.997
URL     : https://musicbrainz.org/release/1e368244-979a-4804-9ea5-23a255eba1d1
Release : 1e368244-979a-4804-9ea5-23a255eba1d1
Type    : Album
Barcode : 724347517426

Track 1 finished, found 11 Q sub-channels with CRC errors
Track 2 finished, found 11 Q sub-channels with CRC errors
Track 3 finished, found 9 Q sub-channels with CRC errors
Track 4 finished, found 10 Q sub-channels with CRC errors
Track 5 finished, found 11 Q sub-channels with CRC errors
Track 6 finished, found 15 Q sub-channels with CRC errors
Track 7 finished, found 26 Q sub-channels with CRC errors
Track 8 finished, found 16 Q sub-channels with CRC errors
Track 9 finished, found 22 Q sub-channels with CRC errors
Track 10 finished, found 22 Q sub-channels with CRC errors
Track 11 finished, found 22 Q sub-channels with CRC errors
Track 12 finished, found 51 Q sub-channels with CRC errors
INFO:whipper.common.program:changing to working directory /tmp/rip-disc.d3H
INFO:whipper.command.cd:ripping track 1 of 12: 01. Viktoria Tolstoy - Månen tur och retur.flac
INFO:whipper.program.cdparanoia:checksums match, 00d1df1c
INFO:whipper.command.cd:CRCs match for track 1
Peak level: 1.000000                      
Rip quality: 100.00%
Traceback (most recent call last):
  File "/home/freso/.local/share/virtualenvs/whipper-dev/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.4.dev41+g1a1ddd5.d20190214', 'console_scripts', 'whipper')()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/main.py", line 43, in main
    ret = cmd.do()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/cd.py", line 186, in do
    self.doCommand()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/cd.py", line 474, in doCommand
    _ripIfNotRipped(i + 1)
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/cd.py", line 456, in _ripIfNotRipped
    self.program.saveRipResult()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/common/program.py", line 145, in saveRipResult
    self._presult.persist()
AttributeError: Program instance has no attribute '_presult'
```

**Comment by JoeLametta** [comment]
Oops... probably introduced while solving merge conflicts. It seems it still would have been broken because in https://github.com/whipper-team/whipper/commit/3e79032b63d25d7f2d66a73ad31f9c2db91d390c `saveRipResult()` was removed from `whipper/common/program.py` but two calls to that function remained in `whipper/command/cd.py`.
