### PR TITLE
Fix critical regressions introduced in 3e79032 and 16b0d8d

### LINKED ISSUE #369: "AttributeError: Program instance has no attribute '_presult'" when ripping
https://github.com/whipper-team/whipper/commit/16b0d8dc295d8576f863c39cffc9009d20a63937 introduced code calling `self._presult.persist()` but neither `_presult` nor `persist()` is defined anywhere in the code, causing ripping to fail:

```python-traceback
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
eject: Cd-rom-kommandoen luk skuffen mislykkedes: Inddata/uddata-fejl
Track 1 finished, found 11 Q sub-channels with CRC errors
Track 2 finished, found 9 Q sub-channels with CRC errors
Track 3 finished, found 9 Q sub-channels with CRC errors
Track 4 finished, found 13 Q sub-channels with CRC errors
Track 5 finished, found 10 Q sub-channels with CRC errors
Track 6 finished, found 13 Q sub-channels with CRC errors
Track 7 finished, found 24 Q sub-channels with CRC errors
Track 8 finished, found 17 Q sub-channels with CRC errors
Track 9 finished, found 18 Q sub-channels with CRC errors
Track 10 finished, found 17 Q sub-channels with CRC errors
Track 11 finished, found 23 Q sub-channels with CRC errors
Track 12 finished, found 47 Q sub-channels with CRC errors
CDDB disc id: a00c300c
MusicBrainz disc id hbJzXWQkBk3ZvIquY7axbmk4f.I-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+12+234197+150+19022+32740+57727+80737+98750+120870+139937+161450+179300+195412+214337&tracks=12&id=hbJzXWQkBk3ZvIquY7axbmk4f.I-
Disc duration: 00:52:00.626, 12 audio tracks

Matching releases:

Artist  : Viktoria Tolstoy
Title   : För älskad
Duration: 00:51:59.997
URL     : https://musicbrainz.org/release/1e368244-979a-4804-9ea5-23a255eba1d1
Release : 1e368244-979a-4804-9ea5-23a255eba1d1
Type    : Album
Barcode : 724347517426

Track 1 finished, found 11 Q sub-channels with CRC errors
Track 2 finished, found 11 Q sub-channels with CRC errors
Track 3 finished, found 9 Q sub-channels with CRC errors
Track 4 finished, found 10 Q sub-channels with CRC errors
Track 5 finished, found 11 Q sub-channels with CRC errors
Track 6 finished, found 15 Q sub-channels with CRC errors
Track 7 finished, found 26 Q sub-channels with CRC errors
Track 8 finished, found 16 Q sub-channels with CRC errors
Track 9 finished, found 22 Q sub-channels with CRC errors
Track 10 finished, found 22 Q sub-channels with CRC errors
Track 11 finished, found 22 Q sub-channels with CRC errors
Track 12 finished, found 51 Q sub-channels with CRC errors
INFO:whipper.common.program:changing to working directory /tmp/rip-disc.d3H
INFO:whipper.command.cd:ripping track 1 of 12: 01. Viktoria Tolstoy - Månen tur och retur.flac
INFO:whipper.program.cdparanoia:checksums match, 00d1df1c
INFO:whipper.command.cd:CRCs match for track 1
Peak level: 1.000000                      
Rip quality: 100.00%
Traceback (most recent call last):
  File "/home/freso/.local/share/virtualenvs/whipper-dev/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.4.dev41+g1a1ddd5.d20190214', 'console_scripts', 'whipper')()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/main.py", line 43, in main
    ret = cmd.do()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/cd.py", line 186, in do
    self.doCommand()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/cd.py", line 474, in doCommand
    _ripIfNotRipped(i + 1)
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/command/cd.py", line 456, in _ripIfNotRipped
    self.program.saveRipResult()
  File "/home/freso/.local/share/virtualenvs/whipper-dev/lib/python2.7/site-packages/whipper-0.7.4.dev41+g1a1ddd5.d20190214-py2.7.egg/whipper/common/program.py", line 145, in saveRipResult
    self._presult.persist()
AttributeError: Program instance has no attribute '_presult'
```

### PR DESCRIPTION
**Pull request by JoeLametta**
Fixes #369.

### CODE REVIEW

**Comment by Freso** [comment]
I'll do a test run later/tomorrow.

**Comment by Freso** [comment]
Ripping at least works as of https://github.com/whipper-team/whipper/pull/371/commits/45ebcea345b2bc0d2d8a99ee0aaf3945d60e77f0 :
```
> whipper cd rip -O "~/tmp/" -W "~/tmp/"
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr1
eject: Cd-rom-kommandoen luk skuffen mislykkedes: Inddata/uddata-fejl
Track 1 finished, found 11 Q sub-channels with CRC errors
Track 2 finished, found 12 Q sub-channels with CRC errors
Track 3 finished, found 10 Q sub-channels with CRC errors
Track 4 finished, found 11 Q sub-channels with CRC errors
Track 5 finished, found 11 Q sub-channels with CRC errors
Track 6 finished, found 14 Q sub-channels with CRC errors
Track 7 finished, found 25 Q sub-channels with CRC errors
Track 8 finished, found 16 Q sub-channels with CRC errors
Track 9 finished, found 21 Q sub-channels with CRC errors
Track 10 finished, found 22 Q sub-channels with CRC errors
Track 11 finished, found 23 Q sub-channels with CRC errors
Track 12 finished, found 50 Q sub-channels with CRC errors
CDDB disc id: a00c300c
MusicBrainz disc id hbJzXWQkBk3ZvIquY7axbmk4f.I-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+12+234197+150+19022+32740+57727+80737+98750+120870+139937+161450+179300+195412+214337&tracks=12&id=hbJzXWQkBk3ZvIquY7axbmk4f.I-
Disc duration: 00:52:00.626, 12 audio tracks

Matching releases:

Artist  : Viktoria Tolstoy
Title   : För älskad
Duration: 00:51:59.997
URL     : https://musicbrainz.org/release/1e368244-979a-4804-9ea5-23a255eba1d1
Release : 1e368244-979a-4804-9ea5-23a255eba1d1
Type    : Album
Barcode : 724347517426

Track 1 finished, found 11 Q sub-channels with CRC errors
Track 2 finished, found 11 Q sub-channels with CRC errors
Track 3 finished, found 10 Q sub-channels with CRC errors
Track 4 finished, found 12 Q sub-channels with CRC errors
Track 5 finished, found 12 Q sub-channels with CRC errors
Track 6 finished, found 15 Q sub-channels with CRC errors
Track 7 finished, found 25 Q sub-channels with CRC errors
Track 8 finished, found 16 Q sub-channels with CRC errors
Track 9 finished, found 21 Q sub-channels with CRC errors
Track 10 finished, found 23 Q sub-channels with CRC errors
Track 11 finished, found 28 Q sub-channels with CRC errors
Track 12 finished, found 55 Q sub-channels with CRC errors
INFO:whipper.common.program:changing to working directory /home/freso/tmp/
INFO:whipper.command.cd:ripping track 1 of 12: 01. Viktoria Tolstoy - Månen tur och retur'.flac
INFO:whipper.program.cdparanoia:checksums match, 00d1df1c
INFO:whipper.command.cd:CRCs match for track 1
Peak level: 1.000000                      
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 2 of 12: 02. Viktoria Tolstoy - Varken ängel eller gud'.flac
INFO:whipper.program.cdparanoia:checksums match, 02a9cccb
INFO:whipper.command.cd:CRCs match for track 2
Peak level: 1.000000                      
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 3 of 12: 03. Viktoria Tolstoy - 3 dygn i rad'.flac
INFO:whipper.program.cdparanoia:checksums match, 20c9b735
INFO:whipper.command.cd:CRCs match for track 3
Peak level: 0.999969                      
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 4 of 12: 04. Viktoria Tolstoy - En bra dag'.flac
INFO:whipper.program.cdparanoia:checksums match, d575c595
INFO:whipper.command.cd:CRCs match for track 4
Peak level: 0.999969                      
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 5 of 12: 05. Viktoria Tolstoy - Och om jag gav'.flac
INFO:whipper.program.cdparanoia:checksums match, 4773d23e
INFO:whipper.command.cd:CRCs match for track 5
Peak level: 0.888123                      
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 6 of 12: 06. Viktoria Tolstoy - Lyckligt slut'.flac
INFO:whipper.program.cdparanoia:checksums match, 76be8b1c
INFO:whipper.command.cd:CRCs match for track 6
Peak level: 1.000000                      
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 7 of 12: 07. Viktoria Tolstoy - Stanna här hos mig _Mama Had to Tell Me_'.flac
INFO:whipper.program.cdparanoia:checksums match, 3bf9684d
INFO:whipper.command.cd:CRCs match for track 7
Peak level: 1.000000                      
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 8 of 12: 08. Viktoria Tolstoy - Du är bäst _i alla fall bra för mig_'.flac
INFO:whipper.program.cdparanoia:checksums match, d6f19a6f
INFO:whipper.command.cd:CRCs match for track 8
Peak level: 0.999878                      
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 9 of 12: 09. Viktoria Tolstoy - September igen'.flac
INFO:whipper.program.cdparanoia:checksums match, d501a2e5
INFO:whipper.command.cd:CRCs match for track 9
Peak level: 0.999939                      
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 10 of 12: 10. Viktoria Tolstoy - Moln i din hand'.flac
INFO:whipper.program.cdparanoia:checksums match, b70ea65c
INFO:whipper.command.cd:CRCs match for track 10
Peak level: 1.000000                       
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 11 of 12: 11. Viktoria Tolstoy - För älskad'.flac
INFO:whipper.program.cdparanoia:checksums match, 12295a74
INFO:whipper.command.cd:CRCs match for track 11
Peak level: 1.000000                       
Rip quality: 100.00%
INFO:whipper.command.cd:ripping track 12 of 12: 12. Viktoria Tolstoy - Det finaste som finns'.flac
INFO:whipper.program.cdparanoia:checksums match, 1e1a2c29
INFO:whipper.command.cd:CRCs match for track 12
Peak level: 0.774536                       
Rip quality: 100.00%
INFO:whipper.image.cue:parsing .cue file u'/home/freso/tmp/Viktoria Tolstoy - F\xf6r \xe4lskad (1996) [FLAC]/Viktoria Tolstoy - F\xf6r \xe4lskad.cue'
INFO:whipper.common.program:3 AccurateRip response(s) found
track  1: rip accurate     (max confidence     15) v1 [b4ac6a14], v2 [62c782b7], DB [b4ac6a14, 62c782b7]
track  2: rip accurate     (max confidence     15) v1 [19d206af], v2 [136cbabb], DB [19d206af, 136cbabb]
track  3: rip accurate     (max confidence     16) v1 [303ddb80], v2 [5c1e7658], DB [303ddb80, 5c1e7658]
track  4: rip accurate     (max confidence     16) v1 [aeae42ad], v2 [e6bb83d5], DB [aeae42ad, e6bb83d5]
track  5: rip accurate     (max confidence     16) v1 [dc983c0e], v2 [b9526acc], DB [dc983c0e, b9526acc]
track  6: rip accurate     (max confidence     16) v1 [8e820131], v2 [a96861a8], DB [8e820131, a96861a8]
track  7: rip accurate     (max confidence     16) v1 [31c44eea], v2 [07f87feb], DB [31c44eea, 07f87feb]
track  8: rip accurate     (max confidence     16) v1 [71ba947d], v2 [2b1c8df3], DB [71ba947d, 2b1c8df3]
track  9: rip accurate     (max confidence     16) v1 [47815e31], v2 [9ee5cd4a], DB [47815e31, 9ee5cd4a]
track 10: rip accurate     (max confidence     16) v1 [49c7dfb4], v2 [dafa4024], DB [49c7dfb4, dafa4024]
track 11: rip accurate     (max confidence     16) v1 [f0e507ff], v2 [a85faee8], DB [f0e507ff, a85faee8]
track 12: rip accurate     (max confidence     15) v1 [afc06931], v2 [7ace7b72], DB [afc06931, 7ace7b72]
```

**Comment by JoeLametta** [comment]
> Ripping at least works as of [45ebcea](https://github.com/whipper-team/whipper/commit/45ebcea345b2bc0d2d8a99ee0aaf3945d60e77f0)

All right, thanks for the test!
